# Classes and Instances 

Classes and Instances by Corey Schafer [youtube](https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc) 

Classes and Objects with Python - Part 1 (Python Tutorial #9) by CS Dojo [youtube](https://www.youtube.com/watch?v=wfcWRAxRVBA&index=9&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg) [code](https://www.csdojo.io/python9)

Classes and Objects with Python - Part 2 (Python Tutorial #10) by CS Dojo [youtube](https://www.youtube.com/watch?v=WOwi0h_-dfA&index=10&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg) [code](https://www.csdojo.io/python10)

Introduction to Classes and Objects - Part 1 (Data Structures & Algorithms #3) by CS Dojo [youtube](https://www.youtube.com/watch?v=8yjkWGRlUmY)

<a href="#멍청하게-클래스-사용하기">멍청하게 클래스 사용하기</a>

<a href="#스마트하게-클래스-사용하기">스마트하게 클래스 사용하기</a>

<a href="#메쏘드와-어트리뷰트">메쏘드와 어트리뷰트</a>

<a href="#클래스를-만들때-self를-빼면-안되요">클래스를 만들때 self를 빼면 안되요</a>

<a href="#클래스를-만들때-self를-빼면-안되는-이유">클래스를 만들때 self를 빼면 안되는 이유</a>

<a href="#객체와-인스턴스의-차이">객체와 인스턴스의 차이</a>

<img src="https://docs.sencha.com/extjs/6.2.0/guides/other_resources/images/classes_instances.png"/>

> 클래스: 인스턴스를 만드는 블루프린트
    
> 인스턴스: 클래스라는 블루프린트를 따라 만들어낸 객체 

> 어트리뷰트: 인스턴스 변수. By the way, I use the word attribute for any name following a dot — for example, in the expression ```z.real```, ```real``` is an attribute of the object ```z```. https://docs.python.org/2/tutorial/classes.html

> 메쏘드: 인스턴스들에 특화된 함수.

# 멍청하게 클래스 사용하기

##### 클래스 만들기

In [1]:
# class Employee:
    
# SyntaxError: unexpected EOF while parsing

SyntaxError: unexpected EOF while parsing (<ipython-input-1-443b0a7e8f38>, line 3)

위와 같이 클래스를 정의만 하고, 아무 것도 쓰지 않으면 에러가 나와요.
임시로 클래스를 엠프티하게 유지하고 싶으면, ```pass```라고 아래와 같이 쓰세요.

In [2]:
class Employee:
    pass

##### 인스턴스 만들기

In [3]:
emp_1 = Employee()
emp_2 = Employee()

In [4]:
print(emp_1)
print(emp_2)

위 아웃풋에서 ```0x111fa8eb8```는 메모리 위치를 의미합니다.
```__main__.Employee object```인 ```emp_1```가 이 위치에 저장되어 있다는 이야기죠.

##### 어트리뷰트 수동으로 만들어 사용하기 - 수트핏!!!

In [5]:
emp_1.first = 'Sungchul'
emp_1.last = 'Lee'
emp_1.email = 'sungchul@yonsei.ac.kr'
emp_1.pay = 150000

emp_2.first = 'Test'
emp_2.last = 'User'
emp_2.email = 'Test.User@email.com'
emp_2.pay = 60000

In [6]:
print(emp_1.email)
print(emp_2.email)

sungchul@yonsei.ac.kr
Test.User@email.com


[<a href="#Classes-and-Instances">Back to top</a>]

# 스마트하게 클래스 사용하기

##### 클래스 만들기

인스턴스 만들때 입력되는 정보를 이용, 어트리뷰트를 자동으로 만들도록 클라스를 만들어요.

In [7]:
# class Employee:
#     pass


class Employee:

    # init method or constructor (initialization)
    def __init__(self, first, last, email, pay):
        # first = "Sungchul"
        # last = "Lee"
        # email = "sungchul@yonsei.ac.kr"
        # pay = 150000 
        
        # emp_1.first = 'Sungchul'
        self.first = first 
        
        # emp_1.last = 'Lee'
        self.last = last
        
        # emp_1.email = 'sungchul@yonsei.ac.kr'
        self.email = email
        
        # emp_1.pay = 150000
        self.pay = pay 

##### 인스턴스 만들기  

인스턴스를 만들때, 인스턴스의 어트리뷰트에 들어갈 정보를 입력하도록 클래스를 만들어요.
이 정보를 이용, 어트리뷰트를 만들도록 클래스를 만들죠.
자동으로 어트리뷰트가 생성되겠죠.

In [8]:
# emp_1 = Employee()

# emp_1.first = 'Sungchul'
# emp_1.last = 'Lee'
# emp_1.email = 'sungchul@yonsei.ac.kr'
# emp_1.pay = 150000

emp_1 = Employee('Sungchul', 'Lee', 'sungchul@yonsei.ac.kr', 150000) # self = emp_1

##### 어트리뷰트 (자동으로 만들어) 사용하기

In [9]:
print(emp_1.email)

sungchul@yonsei.ac.kr


```emp_1.__dict__```을 보면, ```emp_1```의 어트리뷰트가 dictionary로 정리되어 있어요. 

In [10]:
print(emp_1.__dict__)

{'last': 'Lee', 'pay': 150000, 'email': 'sungchul@yonsei.ac.kr', 'first': 'Sungchul'}


##### 메쏘드 사용하기

In [11]:
print('{} {}'.format(emp_1.first, emp_1.last))

Sungchul Lee


In [12]:
class Employee:

    def __init__(self, first, last, email, pay):
        self.first = first 
        self.last = last
        self.email = email
        self.pay = pay 

    # method
    def fullname(self):
        return '{} {}'.format(self.first, self.last)

In [13]:
emp_1 = Employee('Sungchul', 'Lee', 'sungchul@yonsei.ac.kr', 150000)
print(emp_1.email) # sungchul@yonsei.ac.kr
print(emp_1.fullname()) # Sungchul Lee

sungchul@yonsei.ac.kr
Sungchul Lee


[<a href="#Classes-and-Instances">Back to top</a>]

# 메쏘드와 어트리뷰트

> 메쏘드: 끝에 괄호가 있어요. 함수니까 아규먼트를 받겠죠. 괄호는 아규먼트를 받는 주머니죠.
    
```
emp_1.fullname()
```
    
> 어트리뷰트: 끝에 괄호가 없어요. 변수니까 아규먼트를 받을 주머니가 없죠. 
    
```
emp_1.pay
```

메쏘드를 작동시켜보죠.

In [14]:
print(emp_1.fullname())

Sungchul Lee


잘 작동하네요.

괄호를 빼고 작동시켜 볼까요.

In [15]:
print(emp_1.fullname)

<bound method Employee.fullname of <__main__.Employee object at 0x112f57e10>>


이것은 메쏘드가 작동한 것이 아니고, 메쏘드 자체를 프린트한 것이에요.
```Employee.fullname```이라는 ```__main__.Employee object```가 ```0x10f735390```에 저장되어 있다는 거에요. 

[<a href="#Classes-and-Instances">Back to top</a>]

# 클래스를 만들때 self를 빼면 안되요

In [16]:
class Employee:

    def __init__(self, first, last, email, pay):
        self.first = first 
        self.last = last
        self.email = email
        self.pay = pay 

    def fullname(): # <--- self를 고의로 뺐어요
        return '{} {}'.format(self.first, self.last)

In [17]:
emp_1 = Employee('Sungchul', 'Lee', 'sungchul@yonsei.ac.kr', 150000)
print(emp_1.email) # sungchul@yonsei.ac.kr

# TypeError: fullname() takes 0 positional arguments but 1 was given
print(emp_1.fullname())

sungchul@yonsei.ac.kr


TypeError: fullname() takes 0 positional arguments but 1 was given

In [19]:
class Employee:

    def __init__(self, first, last, email, pay):
        self.first = first 
        self.last = last
        self.email = email
        self.pay = pay 

    def fullname(self): 
        return '{} {}'.format(self.first, self.last)

In [20]:
emp_1 = Employee('Sungchul', 'Lee', 'sungchul@yonsei.ac.kr', 150000)
print(emp_1.email) # sungchul@yonsei.ac.kr
print(emp_1.fullname()) # Sungchul Lee
print(Employee.fullname(emp_1)) # Sungchul Lee

sungchul@yonsei.ac.kr
Sungchul Lee
Sungchul Lee


위 에러 메세지를 보면
```fullname() takes 0 positional arguments```, 즉 클래스를 정의할 때 ```fullname()```이라는 함수는 포지션널 아규머트를 받지 않도록 만들었어요.
그런데
```but 1 was given```, 즉 ```emp_1```이 포지션널 아규머트로 ```fullname()```이라는 함수에 들어 왔다는 이야기에요.
함수가 아규먼트를 받지 않도록 구성했는데 아규먼트가 들어오니까 난리가 난거죠.

[<a href="#Classes-and-Instances">Back to top</a>]

# 클래스를 만들때 self를 빼면 안되는 이유

In [28]:
class Employee:

    def __init__(self, first, last, email, pay):
        self.first = first 
        self.last = last
        self.email = email
        self.pay = pay 

    def fullname(self): 
        return '{} {}'.format(self.first, self.last)
    
    def __add__(self, self2):
        return '{} {}'.format(self.first, self2.last) 

In [29]:
emp_1 = Employee('Sungchul', 'Lee', 'sungchul@yonsei.ac.kr', 150000)
print(emp_1.email) # sungchul@yonsei.ac.kr
print(emp_1.fullname()) # Sungchul Lee
print(Employee.fullname(emp_1)) # Sungchul Lee
print(emp_1 + emp_1) # Sungchul Lee

sungchul@yonsei.ac.kr
Sungchul Lee
Sungchul Lee
Sungchul Lee


In [30]:
emp_2 = Employee('Sookkyung', 'Kim', 'sook@gmail.com', 250000)
print(emp_2.email) # sook@gmail.com
print(emp_2.fullname()) # Sookkyung Kim
print(Employee.fullname(emp_2)) # Sookkyung Kim
print(emp_1 + emp_2) # Sungchul Kim

sook@gmail.com
Sookkyung Kim
Sookkyung Kim
Sungchul Kim


In [24]:
print(type(emp_1))

<class '__main__.Employee'>


In [25]:
print(1 + 1) # 2
print("1" + "1") # "11"

2
11


우리가 보통 메쏘드를 다음과 같이 쓰죠.

In [31]:
print(emp_1.fullname)

<bound method Employee.fullname of <__main__.Employee object at 0x1130cff98>>

In [32]:
print(emp_1.fullname())

Sungchul Lee


하지만 파이쎤 내부에서는 아래와 같이 돌아가요.
인스턴스 이름이 괄호 안에 들어가죠.
인스턴스 이름은 그때 그때 변하니까, 이를 대표해서 ```self```라 하고 이를 메쏘드의 첫번째 아규먼트로 집어넣는거죠.

In [33]:
print(Employee.fullname(emp_1))

Sungchul Lee


[<a href="#Classes-and-Instances">Back to top</a>]

In [34]:
import numpy as np

A = np.array([[1.,2.],[3.,4.]])
B = np.eye(2)

print(A)
print(B)
print(A@B)
print(np.matmul(A,B))
print(A.dot(B))
print(type(A))
print(np.ndarray.dot(A,B))

[[1. 2.]
 [3. 4.]]
[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>
[[1. 2.]
 [3. 4.]]


In [35]:
import numpy as np

a = np.arange(10)
print(a)
print(a.dtype)
print(a.shape)

try:
    b = range(10)
    print(b)
    print(b.dtype)
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)
range(0, 10)
'range' object has no attribute 'dtype'
